version: "3.8"
services:
  
  database:
    container_name: "database"
    image: postgres:16.3-alpine
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_DB: platform_api_db
      POSTGRES_USER: sigtunnel
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./scripts/database/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh

  aws-cognito:
    container_name: aws-cognito
    image: sigtunnel/aws_cognito:1.0
    environment:
      OPEN_ID_JWKS_URI_HOSTNAME: "aws-cognito"
      OPEN_ID_JWKS_URI_PORT: "9229"
      OPEN_ID_ISSUER_HOSTNAME: "localhost"
      OPEN_ID_ISSUER_PORT: "9229"
    volumes:
      - .cognito:/app/.cognito
    ports:
      - "9229:9229"

  platform-api:
    container_name: platform-api
    build:
      context: ../platform-api
      dockerfile: src/main/docker/Dockerfile.dev
      args:
        QUARKUS_PROFILE_BUILD_TIME: "localdev"
        QUARKUS_PROFILE_RUN_TIME: "localdev"
    environment:
      QUARKUS_PROFILE_RUN_TIME: "localdev"
      AWS_PROFILE: "sigtunnel-dev"
      AWS_PAGER: ""
    volumes:
      - platform-api-gradle-cache:/root/.gradle
      - ../platform-api/src:/app/src
      - ../platform-api/gradle:/app/gradle
      - ../platform-api/build.gradle:/app/build.gradle
      - ../platform-api/gradle.properties:/app/gradle.properties
      - ../platform-api/settings.gradle:/app/settings.gradle
      - /home/vagrant/.aws/:/root/.aws:ro
      - /home/vagrant/.aws/:/home/jboss/.aws:ro
    depends_on:
      - database
      - aws-cognito
    ports:
     - "8080:8080"
     - "5005:5005" # Debugging port

  platform-frontend:
    container_name: platform-frontend
    build:
      context: ../platform-frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ../platform-frontend/src:/app/src
      - ../platform-frontend/public:/app/public
      - ../platform-frontend/index.html:/app/index.html
      - ../platform-frontend/.eslintrc.cjs:/app/.eslintrc.cjs
      - ../platform-frontend/package.json:/app/package.json
      - ../platform-frontend/package-lock.json:/app/package-lock.json
      - ../platform-frontend/tsconfig.json:/app/tsconfig.json
      - ../platform-frontend/tsconfig.node.json:/app/tsconfig.node.json
      - ../platform-frontend/vite.config.ts:/app/vite.config.ts
      - ../platform-frontend/.env.localdev:/app/.env.localdev
      - ../platform-frontend/.env.development:/app/.env.development
    ports:
      - "3000:3000"

  # material-kit-react-main:
  #   container_name: material-kit-react-main
  #   build:
  #     context: ../Minimal_TypeScript_v6.1.0/vite-ts
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ../Minimal_TypeScript_v6.1.0/vite-ts:/app
  #     - /app/node_modules
  #   ports:
  #     - "3001:8080"

volumes:
  database-data:
    driver: local
  platform-api-gradle-cache:
    driver: local
