FROM node:18-alpine

WORKDIR /app

# Install Git (used by vite build)
RUN apk add --no-cache git

COPY ./package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "dev", "--", "--host"]